config/routes.rb
Galex::Application.routes.draw do
  root 'home#index'
  resources :user_sessions
  resources :documents
  resources :users
  resource :search, only: :create
  match 'signout', to: 'user_sessions#destroy', via: :delete
  match '/documents/:id/download', to: 'documents#download', via: :get, as: :download_document
  match '/documents/:id/upload', to: 'documents#upload', via: :get, as: :upload_document
  match '/documents/new/markdown', to: 'documents#new_markdown', via: :get, as: :new_markdown_document
  match '/documents/new/markdown', to: 'documents#commit_markdown', via: :post, as: :commit_markdown_document
  match '/documents/:id/upload/file', to: 'documents#upload_file', via: :get, as: :update_document_with_file
  match '/documents/:id/upload/file', to: 'documents#commit_upload_file', via: :post, as: :commit_document_update_with_file
  match '/documents/:id/upload/markdown', to: 'documents#upload_markdown', via: :get, as: :update_document_with_markdown
  match '/documents/:id/upload/markdown', to: 'documents#commit_upload_markdown', via: :post, as: :commit_document_update_with_markdown

end

app/models/document.rb
class Document < ActiveRecord::Base
  PERMITTED_FORMATS = [
    "application/vnd.oasis.opendocument.text",
    "application/pdf",
    "application/x-pdf", 
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/msword"
  ]
  attr_accessor :file, :content, :kind_of_document
  
  validates_presence_of :title, :description, :guid, :format
  before_validation :fill_guid, :set_document_format
  validate :check_document_kind
  
  belongs_to :user
  has_many :reads
  has_many :readers, through: :reads, source: :user
  
  # --- methods for tracking dirty state.
  def file=(value)
    attribute_will_change!('file') if file != value
    @file = value
  end
  
  def file_changed?
    changed.include?('file')
  end
  
  def content=(value)
    attribute_will_change!('content') if content != value
    @content = value
  end
  
  def content_changed?
    changed.include?('content')
  end
  # --- end
  
  
  def dissemination_rate 
    ((readers.size.to_f / User.all.size.to_f) * 100).to_i
  end
  
  def belongs_to_user? user
    id = nil
    if user.is_a? User
      id = user.id
    elsif user.is_a? Integer
      id = user
    end
    raise ArgumentError, "User must be either a (existing) User or an Integer" if id == nil
    document.user_id == id
  end
  
  def title_slug
    title.underscore.parameterize
  end
  
  private
  def fill_guid
    self.guid = SecureRandom.uuid unless self.guid.present?
  end
  
  def set_document_format
    if self.file_changed? && !self.content_changed?
      self.format = File.extname(self.file.original_filename).split('.')[1] if self.file.present? && self.file.is_a?(ActionDispatch::Http::UploadedFile)
    elsif !self.file_changed? && self.content_changed?
      self.format = "pdf"
    elsif self.file_changed? && self.content_changed?
      raise ArgumentError, "Detected changes to self.file and self.content. Galex don't know which of them it will store!"
    end
  end
  
  def check_document_kind
    if new_record? || (self.file_changed? || self.content_changed?)
      self.kind_of_document = self.kind_of_document.to_sym

      if(self.kind_of_document != :file && self.kind_of_document != :markdown)
        raise ArgumentError, "New documents must be marked as :file or :markdown through kind_of_document variable."
      else
        if self.kind_of_document == :file
          unless self.file.present?
            self.errors.add(:file, "You must select a file to be uploaded.")
          else
            self.errors.add(:file, "Only odt, doc, docx and pdf files are supported.")  unless PERMITTED_FORMATS.include?(self.file.content_type)
          end
        else 
          unless self.content.present?
            self.errors.add(:content, "Please enter the document's body.")
          else
            self.errors.add(:content, "Please enter the document's body.") if self.content.empty?
          end
            
        end
      end
    end
  end
end

app/controllers/documents_controller.rb
require 'rdiscount'
require 'pdfkit'

class DocumentsController < ApplicationController
  before_filter :require_auth 
 
  
  def index
    redirect_to root_path
  end
  
  def show
    @document = Document.find(params[:id])
    @size = File.size(document_path @document)
  end
  
  def new 
    @document = current_user.documents.build(kind_of_document: :file)
  end
  
  def new_markdown
    @document = current_user.documents.build(kind_of_document: :markdown)
    @post_to = commit_markdown_document_path
    render :new
  end
  
  def commit_markdown
    @document = current_user.documents.build(document_markdown_params)
    unless @document.save!
      render :new
    else
      @document.readers.append current_user
      html = RDiscount.new(@document.content).to_html
      kit = PDFKit.new(html)
      kit.stylesheets << stylesheet_path("uikit.almost-flat")
      file = kit.to_file(document_path(@document))
      redirect_to @document
    end
  end
  
  def create
    params = document_params
    @document = current_user.documents.build(document_params)
    
    render :new unless @document.valid?
    
    if @document.save!
      handle_io_operations @document
      @document.readers.append(current_user)
      redirect_to @document
    else
      @document.errors.add(:base, "Galex failed to store your document. Please try again.")
      render :new
    end
    
  end
  
  
  def edit
    @document = current_user.documents.find(params[:id])
  end
  
  def update
    @document = current_user.documents.find(params[:id])
    render :edit unless @document.update_attributes(document_params)
    redirect_to @document
  end
  
  def destroy
    @document = current_user.documents.find(params[:id])
    if @document.destroy!
      File.delete document_path(@document)
      redirect_to root_path, flash: { success: "Your document, \"#{@document.title}\" was destroyed." }
    else
      render :show, error: "Could not destroy document. Try again."
    end
  end
  
  def upload
    @document = current_user.documents.find(params[:id])
  end
  
  def upload_markdown
    @document = current_user.documents.find(params[:id])
    @document.kind_of_document = :markdown
  end
  
  def commit_upload_markdown
    @document = current_user.documents.find(params[:id])
    @document.kind_of_document = :markdown
    @document.content = params[:document][:content]
    unless @document.valid?
      render :upload_markdown
    else
      @document.touch
      @document.reads.where.not(user_id: @document.user_id).destroy_all
      html = RDiscount.new(@document.content).to_html
      kit = PDFKit.new(html)
      kit.stylesheets << stylesheet_path("uikit.almost-flat")
      file = kit.to_file(document_path(@document))
      redirect_to @document
    end
  end
  
  def upload_file
    @document = current_user.documents.find(params[:id])
    @document.kind_of_document = :file
  end
  
  def commit_upload_file
    @document = current_user.documents.find(params[:id])
    @document.kind_of_document = :file
    @document.file = 000 # hackhack
    @document.file = params[:document][:file]
    unless @document.valid? 
      render :upload_file 
    else
      handle_io_operations @document
      @document.reads.where.not(user_id: @document.user_id).destroy_all
      @document.touch
      redirect_to @document, flash: { success: "Your document was overwritten."}
    end
  end
  
  def download
    @document = Document.find(params[:id])
    @document.readers.append(current_user)
    send_file document_path(@document),
      filename: "#{@document.title_slug}.#{@document.format}",
      type: Rack::Mime::MIME_TYPES[".#{@document.format}"]
  end
  
  private
  def fields
    params.require(:document)
  end
  def base_document_params
    [:title, :description, :kind_of_document]
  end
  
  def document_params
    fields.permit(base_document_params + [:file])
  end
  
  def document_upload_params
    fields.permit(:file)
  end
  
  def document_markdown_params
    fields.permit(base_document_params + [:content])
  end
  
  def document_path document
    File.join(Rails.root, "private", "documents", "#{document.guid}.#{document.format}")
  end
  
  def handle_io_operations document
    FileUtils.mv(document.file.tempfile.to_path.to_s, document_path(document))
  end
  
  def stylesheet_path name
    File.join(Rails.root, "vendor", "assets", "stylesheets", "#{name}.css")
  end
  
  
end

app/views/documents/_form.html.erb
<%= form_for(document, url: @post_to, html: { class: 'uk-form uk-form-stacked' }) do |f| %>
    <%= f.hidden_field :kind_of_document %>
    <div class="uk-form-row">
        <%= f.label :title, class: 'uk-form-label' %>
        <div class="uk-form-controls">
            <%= f.text_field :title, placeholder: 'Document title', class: 'uk-form-large' %>
        </div>
    </div>
    <div class="uk-form-row">
        <%= f.label :description, class: 'uk-form-label' %>
        <div class="uk-form-controls">
            <%= f.text_area :description, placeholder: 'Type a description to your document', rows: 5, cols: 50 %>
        </div>
    </div>
    <% if document.kind_of_document == :file %>
        <div class="uk-form-row">
            <%= f.label :file, class: 'uk-form-label' %>
            <div class="uk-form-controls">
                <%= f.file_field :file, class: 'uk-form-large' %>                
            </div>
        </div>
    <% elsif document.kind_of_document == :markdown %>
        <div class="uk-form-row">
            <%= f.label :content, class: 'uk-form-label' %>
            <div class="uk-form-controls">
                <%= f.text_area :content, rows: 5, cols: 50, data: { uk_markdownarea: '' } %>
            </div>
        </div>
    <% end %>
    <div class="uk-form-row">
        <%= f.submit 'Store', class: 'uk-button uk-button-large uk-button-primary'%>
    </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document '<%= @document.title %>'</h1>
<div class="uk-alert uk-alert-warning" data-uk-alert>
    <a href="" class="uk-alert-close uk-close"></a>
    <strong>Hey! Why can't I overwrite a document?</strong> Calm down! You can. Use the <a href="#">Update document</a> feature from the document's page and you're all set!
</div>
<%= render partial: 'partials/form_errors', locals: { model: @document }%>
<%= render partial: 'form', locals: { document: @document }%>

app/views/documents/new.html.erb
<h1>New document</h1>
<%= render partial: 'partials/form_errors', locals: { model: @document }%>
<%= render partial: 'form', locals: { document: @document, to: @post_to }%>

app/views/documents/show.html.erb
<div class="uk-clearfix">
    <div class="uk-float-left">
        <article class="uk-article">
            <h1 class="uk-article-title"><%= @document.title %></h1>
            <p class="uk-article-meta">Uploaded by <%= link_to @document.user.pretty_name, @document.user %>, <%= time_ago_in_words(@document.updated_at)%></p>
            <p class="uk-article-lead"><%= @document.description %></p>
        </article>
    </div>
    <div class="uk-float-right">
        <div class="uk-button-group">
            <%= link_to download_document_path(@document), class: "uk-button uk-button-primary uk-button-large", target: :blank do %>
                <i class="uk-icon-cloud-download"></i> Download
            <% end %>
            <% if current_user_owns? @document %>
                <%= link_to edit_document_path(@document), class: "uk-button uk-button-large" do %>
                    <i class="uk-icon-pencil"></i> Edit
                <% end %>
                <%= link_to document_path(@document), class: "uk-button uk-button-large uk-button-danger", disabled: !current_user_owns?(@document), data: {confirm: 'You\'re about to remove a document from the whole repository. Do you want to continue?'}, method: :delete, action: :delete do %>
                    <i class="uk-icon-trash-o"></i> Delete
                    <% end %>
                <%= link_to upload_document_path(@document), class: "uk-button uk-button-large"  do %>
                    <i class="uk-icon-cloud-upload"></i> Update            
                <% end %>
            <% end %>
        </div>
    </div>
</div>

<hr />
<div class="uk-grid" data-uk-grid-margin="">
    <div class="uk-width-medium-2-3">
        <div class="uk-panel">
            Last updated: <%= @document.updated_at %> (<%= time_ago_in_words(@document.updated_at) %>) <br />
            Size: <%= number_to_human_size(@size) %>
            <hr />
            
        </div>
    </div>
    <div class="uk-width-medium-1-3">
        <div class="uk-panel uk-panel-box">
            <h3 class="uk-panel-title">Versioning</h3>
            <span class="uk-text-muted">This version of Galex has not support to versioning.</span>
        </div>
    </div>
</div>

app/views/documents/upload.html.erb
<h1>Updating document '<%= @document.title %>'</h1>
<center>
    <p>How do you want to update this document?</p>
    <div class="uk-button-group">
        <%= link_to update_document_with_file_path(@document), class: 'uk-button uk-button-large uk-button-primary' do %>
            <i class="uk-icon-cloud-upload"></i> Upload a file from my computer
        <% end %>
        
        <%= link_to update_document_with_markdown_path(@document), class: 'uk-button uk-button-large uk-button-primary' do %>
            <i class="uk-icon-pencil"></i> Write a new document online
        <% end %>
    </div>
</center>

app/views/documents/upload_file.html.erb
<h1>Overwriting document '<%= @document.title %>' with a new file</h1>
<div class="uk-alert uk-alert-large uk-alert-warning">
    <h2>Read carefully before continuing:</h2>
    <p>You're about to overwrite a file from the document's repository. Please notice that this version of Galex you're using
        does not support versioning, which means that the old version of this document will be completely overwritten with
        the version you're about to upload.</p>
    <p>Given this fact, be aware that no rollback or undo is possible, and the actual version of the document will be permanently lost.</p>
</div>
<%= render partial: 'partials/form_errors', locals: { model: @document }%>
<%= form_for @document, 
    url: commit_document_update_with_file_path(@document), 
    method: :post, 
    html: { class: 'uk-form uk-form-stacked' } do |f| %>
    
    <%= f.hidden_field :kind_of_document %>
    <div class="uk-form-row">
        <%= f.label :file, class: 'uk-form-label' %>
        <div class="uk-form-controls">
            <%= f.file_field :file, class: 'uk-form-large' %>
        </div>
    </div>
    <div class="uk-form-row">
        <%= f.submit 'Update', class: 'uk-button uk-button-large uk-button-primary' %>
    </div>
<% end %>

app/views/documents/upload_markdown.html.erb
<h1>Overwriting document '<%= @document.title %>' with a new file</h1>
<div class="uk-alert uk-alert-large uk-alert-warning">
    <h2>Read carefully before continuing:</h2>
    <p>You're about to overwrite a file from the document's repository. Please notice that this version of Galex you're using
        does not support versioning, which means that the old version of this document will be completely overwritten with
        the version you're about to upload.</p>
    <p>Given this fact, be aware that no rollback or undo is possible, and the actual version of the document will be permanently lost.</p>
</div>
<%= render partial: 'partials/form_errors', locals: { model: @document }%>
<%= form_for @document, 
    url: commit_document_update_with_markdown_path(@document), 
    method: :post, 
    html: { class: 'uk-form uk-form-stacked' } do |f| %>
    
    <%= f.hidden_field :kind_of_document %>
    <div class="uk-form-row">
        <%= f.label :content, class: 'uk-form-label' %>
        <div class="uk-form-controls">
            <%= f.text_area :content, class: 'uk-form-large', data: { uk_markdownarea: '' } %>
        </div>
    </div>
    <div class="uk-form-row">
        <%= f.submit 'Update', class: 'uk-button uk-button-large uk-button-primary' %>
    </div>
<% end %>