config/routes.rb
Galex::Application.routes.draw do
  root 'home#index'
  resources :user_sessions
  resources :documents
  resources :users
  resource :search, only: :create
  match 'signout', to: 'user_sessions#destroy', via: :delete
  match '/documents/:id/download', to: 'documents#download', via: :get, as: :download_document
  match '/documents/:id/upload', to: 'documents#upload', via: :get, as: :upload_document
  match '/documents/new/markdown', to: 'documents#new_markdown', via: :get, as: :new_markdown_document
  match '/documents/new/markdown', to: 'documents#commit_markdown', via: :post, as: :commit_markdown_document
  match '/documents/:id/upload/file', to: 'documents#upload_file', via: :get, as: :update_document_with_file
  match '/documents/:id/upload/file', to: 'documents#commit_upload_file', via: :post, as: :commit_document_update_with_file
  match '/documents/:id/upload/markdown', to: 'documents#upload_markdown', via: :get, as: :update_document_with_markdown
  match '/documents/:id/upload/markdown', to: 'documents#commit_upload_markdown', via: :post, as: :commit_document_update_with_markdown

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Galex</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="uk-navbar">
        <div class="uk-container uk-container-center">
            <%= link_to "Galex", root_path, class: 'uk-navbar-brand' %>
            <% if user_signed? %>
            	<ul class="uk-navbar-nav">
            	    <li><%= link_to 'Repository', root_path %></li>
            	    <li><%= link_to 'Users', users_path %></li>
            	    <li class="uk-parent" data-uk-dropdown>
            	        <a href>New <i class="uk-icon-caret-down"></i></a>
            	        <div class="uk-dropdown uk-dropdown-navbar">
            	            <ul class="uk-nav uk-nav-navbar">
            	                <li><%= link_to "Upload", new_document_path %></li>
            	                <li><%= link_to "Write now", new_markdown_document_path %></li>
            	            </ul>
            	        </div>
            	    </li>
            	</ul>
            	<div class="uk-navbar-flip">
            		<div class="uk-navbar-content">
            	    <ul class="uk-navbar-nav">
            	        <li class="uk-parent" data-uk-dropdown>
            	            <a href><%= current_user.pretty_name %> <i class="uk-icon-caret-down"></i></a> 
            	            <div class="uk-dropdown uk-dropdown-navbar">
            	                <ul class="uk-nav uk-nav-navbar">
            	                    <li><a href="#">Profile</a></li>
            	                    <li><%= link_to "Sign out", signout_path, method: :delete %></li>
            	                </ul>
            	            </div>
            	        </li>
            	    </ul>
            	    <form class="uk-search" action="<%= search_path %>" method="post" data-uk-search="{source:'<%= search_path(format: :json) %> '}">
            	        <input class="uk-search-field" name="search" type="search" placeholder="Search..." value="<%= params[:search] %>">
            	        <button class="uk-search-close" type="reset"></button>
            	        <input name="authenticity_token" value=" <%= form_authenticity_token %>" type="hidden"> 
            	    </form>
            	</div>
        		</div>
			<% end %>
        </div>

    </nav>
    <div class="uk-container uk-container-center uk-margin-top">
        <% flash.keys.each do |k| %>
        <div class="uk-alert uk-alert-<%= flash_class(k) %>" data-uk-alert>
            <a href class="uk-alert-close uk-close"></a>
            <p><%= flash[k] %></p>
        </div>
        <% end %>
        <%= yield %>
    </div>
</body>
</html>